services:
  db:
    image: postgres:15-alpine
    container_name: print_db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - print_data:/var/lib/postgresql/data
volumes:
  print_data:
