class PrintController < ApplicationController
  def index
  end

  def generate_pdf
    respond_to do |format|
      format.pdf do
        pdf_content = generate_static_pdf

        send_data pdf_content,
                  filename: "static_document.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  private

  def generate_static_pdf
    require "prawn"

    Prawn::Document.new do |pdf|
      pdf.text "Static Document", size: 24, style: :bold, align: :center
      pdf.move_down 20

      pdf.text "This is a sample PDF document generated by Rails!", size: 14
      pdf.move_down 10

      pdf.text "Current Date: #{Date.current.strftime('%B %d, %Y')}", size: 12
      pdf.move_down 10

      pdf.text "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
               "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
               size: 11, align: :justify

      pdf.move_down 20

      pdf.text "Sample Data:", size: 14, style: :bold
      pdf.move_down 10

      table_data = [
        ["Item", "Quantity", "Price"],
        ["Product A", "2", "$10.00"],
        ["Product B", "1", "$25.00"],
        ["Product C", "3", "$5.00"]
      ]

      pdf.table(table_data, header: true) do
        row(0).font_style = :bold
        cells.padding = 8
        cells.borders = [:top, :bottom]
      end

      pdf.move_down 20
      pdf.text "Total: $55.00", size: 14, style: :bold, align: :right

    end.render
  end
end
